### PR TITLE
Small updates v2

### PR DESCRIPTION
**Pull request by bruce34**
Two changes, one to allow command line params to set keys, address, use a different programmer etc. for compiling and flashing. Hopefully the correct fuses this time - only tested on an hr25 (329)

Another to send the time when the master starts - speeds up lock.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
The code looks good to me, but I'm confused a bit about the fuse settings:
 1. Is it really necessary to clear the EESAVE fuse for programming the EEPROM? AFAIK clearing it only causes the EEPROM to be erased during a chip erase (which is don at the start of programming, normally). However, I'd expect you can program EEPROM just fine without erasing it, or isn't that true? Or is it a problem that any unused (e.g. not present in the .eep file) part of the EEPROM is not erased?
 2. The fuse setting you picked for HR25 seem significantly different from the HR20 settings. You enabled the BOOTRST fuse, which causes resets to happen into the bootloader area, but I don't think we're using a bootloader? For the clock fuses, HR20 runs on 8Mhz, but HR20 has CKDIV8 programmed so runs at 1Mhz? The efuse enables the brown-out-detector at 1.7-2.0V, I guess that's ok (running at 2.5-2.9V will probably trigger way before the 2xAA are really empty).

**Comment by KickerTom** [comment]
For Q1, AFAIK every EEPROM needs to be erased before its programmed. So I think you can't program EEPROM without erasing it. That's why the fuse is named EESAVE - it preserves the EEPROM contents during programming, protects EEPROM from changes.

**Comment by KickerTom** [comment]
For Q2, the CKDIV8 should, IMHO, be programmed in both HR20 and HR25. Running the MCU at 8MHz is out of the spec at 3V, so 1MHz is safer for startup. And we don't really care about speed, as the first thing done in main.c is overriding this value and switching to 4MHz via setting the CLKPR register (which is initialized from the CLKDIV8 fuse).
The brown-out-detector is, IMHO, not needed, and it has some impact on power consumption, so I would recommend disabling it.
Regarding BOOTRST and BOOTSZ fuses, I have no idea. I would also say we don't want them, we don't have a bootloader. Bruce, what's the reason for them?

**Comment by KickerTom** [comment]
One more idea, probably out of the scope of this pull request, but nevertheless:
It would be great to have the fuses defined on one place only, and have some comment describing them and why they are at the values they are. As we can see here, it's not always obvious.
At this moment, the fuses are defined in main.c, in this script, in makefile, and maybe on other places as well. And which get's used depends on how you compile and how you flash. That's not right...

**Comment by bruce34** [comment]
Thanks for the replies. With an HR20 with RFM12b attached I have tidied up the script a little more:
- remove bootloader fuses
- 1MHz start up
- remove brown out. I was previously annoyed by the battery removal time before getting a clean boot, but you are right, better gotten rid of.
- added a --dryRun so I could see what was going on.
- added fuse docs inline (from 329 but essentially the same for 169)
- make the fuses the same for the 329/169
- minor fix to compile script

I agree about the fuses being scattered, but as you say, probably one for another day.

I've pushed another change to my fixes branch, but it doesn't seem ideal, I'd rather rebase, squash etc. Let me know if there is a better way.

**Pull request merged**
