### PR TITLE
improve battery reading on startup

### PR DESCRIPTION
**Pull request by c-MM**
Motor calibration will start a few seconds later but battery
	readings are more accurate and don't trigger an early low
	battery warning

### CODE REVIEW

**Comment by c-MM** [comment]
Here is an packet, that I saw, which shows the Problem. The minute is m00 but should be m39 because the RTC was not yet set. You can also see the low battery value of 2.29V in the first packet but in the next packets it is 2.66V.
```
(1c){
-D m00 s17 A V30 I2080 S1700 B2289 E40
-D m43 s17 A V30 I2163 S1700 B2656 E40 W
-D m47 s17 A V30 I2094 S1700 B2656 E40 W
}```

**Comment by c-MM** [comment]
I did some more tests on this and I'm unsure on how to proceed. The first low reading of the battery is gone, when allow_ADC_during_motor is set to zero.
So it's not a bug in the ADC code but probably poor pcb layout design, as I can only measure a voltage drop of 0.003V at the battery contacts when the motor is running. Maybe this happens only on the "old" HR20 I have. 
So waiting for more samples is probably only hiding a bad electrical design. The best solution might be make zero the default for allow_ADC_during_motor and use ifdefs to enable it on devices where it is known to not affect the battery readings.

**Comment by KickerTom** [comment]
This is interesting find, thanks. In general, I like preventing ADC and motor to run at the same time, if nothing else, just to decrease ADC noise.
However, I again don't understand why you see what you see (sorry, it's getting boring, I know ;-) ).
If I read the code correctly, the motor is checked every second, and started only if battery average is nonzero. AFAICT the battery can't be non-zero before the first ADC measurement finishes. But you found that the problem is with the very first measurement... So how can motor, which is not running, have any effect on ADC?
This is getting more and more strange :-). To complicate things, battery measurement is done three times, first result is discarded, the remaining two are compared and used only if they don't differ too much (which I would say is paranoia :-), but there probably was some reason, so there probably were already some problems with the measurement in the past). So we need two (at least) wrong measurements... Could be maybe interesting to output all the ADC results on serial, to see what values are we getting, how many gets discarded before we get something usable...
Do you see the wrong battery measurement even with the explicit early ADC start you added (without the ringbuffer filter)? ADC should be finished before the first RTC task. Or you can even add some sleep after starting the first ADC measurement to be sure nothing else is running. Will that show wrong battery value as well? What about temperature, is the first measurement OK?
Maybe the ADC initialization has some problem, maybe we are too fast somewhere, making the first (few) measurements wrong...

**Comment by c-MM** [comment]
Thanks for bearing with me. I can research this some more, but my guess at the moment is, that because the motor is starting with motor_pwm_max and slowly decreasing to reach the desired motor speed the current consumption decreases and so does the voltage drop. So if we have the first measurment (which I assume to be correct) the motor starts with the maximum pwm value, leading to some low measurement values that lower the average a lot. The more values we have in the adc ring, the less the motor startup makes a difference. If you look at the schematic, all power is supplied by the unknown IC2 which seems to have a noticable resistance.
I will have to do some soldering to measure the "real" value with some external equipment and compare it to the internal adc values. Until now I just measured at the battery contacts and there I have next to no drop when the motor starts.
I don't know anything about the temperatures at the moment, as I usually touch the valve when flashing and resetting it, so the temperature is probably wrong anyways.

**Comment by KickerTom** [comment]
Thank you for investigating this. You may be right about the motor, as the voltage we see in the first packet is probably not the first measurement, but just average at the time the packet was sent. And first packet is sent after receiving sync etc...
Not sure how much time is this worth. It's just minor issue during startup, which is happening maybe twice a year, when changing batteries? Maybe just disabling ADC during motor would be the best solution after all...

**Comment by c-MM** [comment]
Unfortunatelly I'm wrong on this, but I have no idea where to search further. As you can see I attached my osziloscope to the power and motor line and triggered on the motor start. The two bright spots in the upper trace are the cursors for measurment and they show only a voltage drop of 24mV on the start of the motor.
voltage

Should I make a patch that sets allow_ADC_during_motor per default to false?

**Comment by c-MM** [comment]
Yeah, I found it finaly I guess. At least all the resets (around 10) I did not see lower battery values except a few mV that mach my measurement. This can get closed and is fixed with #22.

**Comment by c-MM** [comment]
Well it seems I have to give up on that.

**Pull request closed without merging**
