### PR TITLE
fix wrong packet during startup and early battery warning

### PR DESCRIPTION
**Pull request by c-MM**
The RTC must be set before setting time_sync_tmo and
	TASK_RTC or a packet with wrong time information can be sent.
	Start the ADC and wait for at least 4 samples to not trigger
	a battery warnig during boot.

### CODE REVIEW

**Comment by c-MM** [comment]
Well in some way they are related as they improve the statup behaviour of the valve, but I can easily split them.

Concerning the ADC change: I consider it neccessay as the ADC readings seem very low when booting the valve. I guess too many things are done and started like motor, rfm12b, led motor sensor, and the avr not sleeping, that we get very low readings on the first try. So during the last days when debugging and flashing a lot I frequently saw a valve start with battery warning with a still good battery. This Problem gets worse when using NiMH cells, where the values between "good" and "low" are very close as 2.5V is good, but 2.3V would be low.

Waiting for 4 samples actually delays the motor startup at main.c:300. During this time "Ad 1" is displayed and it is displayed a few seconds longer then before and the battery low is not triggered as it is equally protected in controller.c:466 by "if (bat_average) { ...". I considered the smallest change to achieve a better startup behaviour as all other ways imply more changes to the logic.

The RTC change is needed since the RTC got set after "task|=TASK_RTC" which tiggered sending a wireless packet with wrong time information. I moved the time_sync_tmo=20 just to have the assignments in one place. Seperating the synchronisation loop from the RTC_s256 access should not matter, as the CPU won't sleep during that time. But I can move the setting of the RTC and time_sync_tmo assignment over the synchronisation loop.

What do you prefer?

**Comment by KickerTom** [comment]
Well, I do not have preference regarding the split, just that if it was split, the first part would be merged by now :-).
I am not opposing the change, I am trying to understand. I actually think that delaying the motor may be a good thing in general.
I just don't think the explanation with everything starting holds, as (if I am not mistaken), the motor starts the soonest after the ADC finishes the first measurement. Also, my experience with batteries is that they are quite hard power source, and the pattern is more like higher voltage if there was no power draw, and slowly going down to some "stable" value after connecting the appliance. Usually no "dips". My suspicion is there is some problem with ADC measurement, and I am afraid we are just hiding it now.
Not sure what to do. I really want to merge this, but I also don't want to lose the information that the first measurement is bad. Wondering if adding a comment to the code would be good, or maybe creating a ticket with some details? What do you think?

**Comment by KickerTom** [comment]
Regarding the second part with timeouts, I still don't understand why your solution helps. My understanding is that time_sync_tmo variable can not be used while wirelessReceivePacket is being executed (it is not accessed in any interrupt, AFAICT) so it does not matter whether you set it early or late. For the task variable, it is the same. It is read only in the main loop, and there is can be used only after returning from wirelessReceivePacket call (which itself is called from the main loop).
To me, this looks more like some race condition, and you changed timing by reordering the code, which made the problem less likely to occur.
But I may be overlooking something obvious. Can you explain the intended effect of this change, please?

**Comment by c-MM** [comment]
Yes, you are right. After rethinking the problem I also don't understand anymore why this seems to help. Even if an interrupt occurs during wirelessReceivePacket, it should not lead to TASK_RTC beeing executed.

**Comment by c-MM** [comment]
I will try some more things regarding the adc. Maybe it might be anyways a good idea not to start anything until we know that the battery voltage is acceptable.

**Comment by matthijskooijman** [comment]
I had a look at the commit and discussion, seems you're on the right track. I'm not familiar enough with the code yet to actually figure out what's going on, though.

As for splitting the commit, I would prefer seeing them split (two commits in one PR is fine). In general, I prefer having a clean and separated history, which makes review and later blaming easier. Also, the commit messages might need a bit more background on the problem, and why this solution helps (once you figure this out ;-p).

**Comment by c-MM** [comment]
Well, I close that request for now and keep watching the behaviour on my valves until I figure out how and if it reallt works.

**Pull request closed without merging**
