### PR TITLE
Source tree and compile options refactoring

### PR DESCRIPTION
**Pull request by MacHoel**
Hi all,

I am proposing to use a bit more the Makefiles to tune and build the software, rather than relying on dummy files and pure compile options.
Looking forward to get feedback.

Cheers,
Hoel

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Woah, a pull request! Apparently I actually have to star the repo to get notified, just creating the repo isn't enough :-)

Thanks for looking into this, I'll try to review your work soon. FYI, I did some work on reorganizing the source tree as well, mainly focusing on sorting out and expanding the documentation. It's been a while, so I'm not sure how far I got, but I'll share that ASAP as well.

**Comment by matthijskooijman** [comment]
Just had a look, this all looks good to me. Great to see small and contained commits, that's how I like my history best ;-p

Some remarks:
 - configCheck forcing a rebuild: I think this might be fixed by making configCheck a PHONY target?
 - Regarding the file ordering for file size - I'm happy to merge the PR and later improve this as well.
 - You have two merge commits in your history, which seem to be pointless and only confused me. Perhaps you could use rebase to flatten the history?

**Comment by matthijskooijman** [comment]
Oh, missed the last three commits. Seems you already solved the configCheck issue there, looks good.

**Comment by KickerTom** [comment]
Is this PR still under development? Haven't seen any activity for a long time. And it would be a pitty to let this slip through, it's quite a lot of good and interesting changes.
I have tried this now (manual merge needed, but nothing difficult), and I can still see the binaries are slightly bigger than original (however, this is with ancient gcc 4.3.3, maybe newer one would be better?). Also, I have problems with assembly listing for files from the common folder not ending up in .lst file in the output directory, but on terminal. (gcc spits warnings like "Warning: can't open HR20_rfm_int_sww/../common/rfm.lst: No such file or directory").
It would be great if this could be cleaned up and merged...

**Comment by matthijskooijman** [comment]
@KickerTom, could you publish your rebased version of these commits somewhere? No need to make a full PR, just push the branch somewhere. Did you get rid of the merge commits in there too?

Also, could you post the original and new .elf files? I want to diff their assembly to see if I can figure out what causes the size difference.

@MacHoel, are you still interested in this? OpenHR20 development has picked up a bit recently, so we should be able to merge this if the last points are fixed. AFAICS, these are:
 - Rebase so it applies to master again (removing the merge commits)
 - Fix the assembly listing issue reported by @KickerTom  
 - @KickerTom, did I miss any?

The size issue is minor I think, we can also further investigate that after merging this PR.

**Comment by c-MM** [comment]
Yes, I can also compile the source with gcc 4.8 and check, what the sizes are.

**Comment by MacHoel** [comment]
Hi I am too back on dev of this.
Could not figure out how to optimize size except by changing the order of obj on link command line.
I have a python script to find out the best order though.
Will try and push this for review soon

**Comment by KickerTom** [comment]
Excellent, thank you. If you'll be making changes, could you, please, split the commits to multiple pull request. This way we can merge what is OK and we don't have to hold back the whole set for just one problematic commit.

**Comment by MacHoel** [comment]
Hi,

I believe only the size issue remains now.

Cheers

**Comment by MacHoel** [comment]
In addition, could we put the rfmsrc content at the root of this repo and remove those good old, legacy, unused in years, folders from the original project ?

I know it's a mess if one needs to rebase their work, but since there are only a few active developers, and they all seem to be watching lately ;) ...

**Comment by KickerTom** [comment]
Just had a quick look, here are first impressions:
   * target thermotronic (after doing "make all"): make[1]: *** No rule to make target `eeprom.c', needed by `thermotronic_sww/eeprom.o'.  Stop.
   * RFM_TUNING default value is changed back from 1 to 0 (this is recent change, need probably update in the patch)

**Comment by KickerTom** [comment]
> RFM_TUNING default value is changed back from 1 to 0 (this is recent change, need probably update in the patch)

Actually, I think any options in the main makefile (rfmsrc/Makefile) are ignored, e.g. changing the SECURITY_KEY has no impact at all.

**Comment by KickerTom** [comment]
Did some more experiments with the size. Object files differ, but it seems only in things like path to source file etc. Nothing important. When using object files generated by this patched version, but linked with the original one, the resulting bin size is the same. So the critical part is linker, as expected.

**Comment by KickerTom** [comment]
> In addition, could we put the rfmsrc content at the root of this repo and remove those good old, legacy, unused in years, folders from the original project ?
>
> I know it's a mess if one needs to rebase their work, but since there are only a few active developers, and they all seem to be watching lately ;) ...

Definitely, we want to do this. But not as part of this PR :-). Also, we need to make sure we carry over all documents and other stuff not present in the rfmsrc folder.

**Comment by MacHoel** [comment]
Did some more experiments with the size. Object files differ, but it seems only in things like path to source file etc. Nothing important. When using object files generated by this patched version, but linked with the original one, the resulting bin size is the same. So the critical part is linker, as expected.
@KickerTom 

I confirm : changing the order of the obj files on the link command is what affects the bin size

**Comment by MacHoel** [comment]
> Actually, I think any options in the main makefile (rfmsrc/Makefile) are ignored, e.g. changing the SECURITY_KEY has no impact at all.

Just did a quick test with `make SECURITY_KEY_0=0x25 thermotronic_sww -j` worked as expected :
avr-gcc -c -mmcu=atmega169 -I. -gdwarf-2 -DF_CPU=1000000UL -DREVISION=\"\" -DRFM=0 -DRFM_BAUD_RATE=19200 -DRFM_DEVICE_ADDRESS=28 -DSECURITY_KEY_0=***0x25*** [...]

So, not sure how you encountered the issue.

However the options specified on each target override the inline ones e.g. specifying `RFM=1` for thermotronic_sww will have no effect indeed (not implemented anyway).
```
thermotronic_sww:
         $(shell mkdir $(DEST)/$@ 2>/dev/null)
         $(MAKE) -C OpenHR20 \
                TARGET=../$(DEST)/$@/hr20 \
                OBJDIR=$@ \
                HW_WINDOW_DETECTION=0 \
                RFM=0 \                                   << OVERRIDES>>
                HW=THERMOTRONIC \
                REV=-DREVISION=\\\"$(REV)\\\"
```
What I can do is replace `VAR=X`with `VAR?=X` whenever this will not cause an error in openHR20/Makefile, e.g. for `HW_WINDOW_DETECTION` in the upper case.

**Comment by KickerTom** [comment]
> So, not sure how you encountered the issue.

I haven't specified anything on commandline. I changed the parameters in OpenHR20\rfmsrc\Makefile and then run "make". Also for thermotronic, just in OpenHR20\rfmsrc folder run "make all", and you will see the compilation error.

**Comment by MacHoel** [comment]
> Also for thermotronic, just in OpenHR20\rfmsrc folder run "make all", and you will see the compilation error.

I pushed fixes for most of the issues you raised, but still cannot replicate the above quoted...
Could you give me more details like your changed Makefile, the output of the failure using -d make option, a log of a find command on your working directory to check its state, the ouput of make -v, anything you can think of that may make the difference !

Thx

**Comment by c-MM** [comment]
Does anyone know, why the linking order makes any differences in size? If it is some padding done by the linker, it might be useful to include your python script, as it might need to be tweaked after every change ton the files which changes the size of some objects.

**Comment by KickerTom** [comment]
> I pushed fixes for most of the issues you raised, but still cannot replicate the above quoted...

Hmm, no idea. I just re-tested, and everything is working fine (even without pulling your latest changes). So probably some mistake on my end, sorry for the noise.

**Comment by dlemper** [comment]
As any issues with this PR seem to be resolved.. Are you going to merge it with master branch?

**Comment by KickerTom** [comment]
I believe only the size issue remains, and that is probably not important enough to hold this back. I think we should merge this. But I had very little time for this project lately, and I don't feel like merging this without proper re-testing. I will try to find some time, but if anyone else steps up and merge it sooner, it would be welcome.

**Comment by dlemper** [comment]
Hi, are there any news on this?
You may just merge this and if something fails or is broken, we can fix that or revert to the state before merging. What do you think?

Thank you for your time!

**Comment by KickerTom** [comment]
You are right. Lets start and deal with the consequences later ;-).

**Pull request merged**
